### ISSUE TITLE
fhirProperties errors [x]

### ISSUE THREAD

**Issue by mvdzel** [mvdzel/vha-ampl-fhir-ig#18]
The pattern for [x] is wrong.

For example:
`MedicationOrder.rate[x].rateRange`
should be
`MedicationOrder.rate[x]`
and
`MedicationOrder.rateRange`

`MedicationOrder.dose[x].doseQuantity`
should be
`MedicationOrder.dose[x]`
and
`MedicationOrder.doseQuantity`

**Comment by jlyle1** [comment]
I don't see any and may have fixed it. Please retest
